server:
  port: 8443
  shutdown: graceful
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: validation-service
        uri: http://localhost:8081
        predicates:
        - Path=/api/validation/**

      - id: github-service
        uri: http://localhost:8082
        predicates:
        - Path=/api/github/**

     