server:
  port: 8082
  shutdown: graceful
github:
  apiUrl: https://api.github.com/
  apiSecret: secret
  apiKey: key
spring:
  application: fargotest
  data:
    mongodb:
      database: test
      auto-index-creation: true
      uri: dpconnectionstring
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
microservices:
  urls:
    validation: http://localhost:8081
    github: http://localhost:8082